from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from enum import Enum
import uuid

class MemoryType(Enum):
    EPISODIC = "episodic"   # What happened (Event-based)
    SEMANTIC = "semantic"   # High-level conclusions (World knowledge)

class EntityType(Enum):
    PERSON = "person"
    OBJECT = "object"
    TEXT = "text" # OCR detections

@dataclass
class BaseObservation:
    """Base fields for anything captured from the video stream."""
    video_id: str
    clip_id: int
    ts_ms: int
    obs_id: str = field(default_factory=lambda: str(uuid.uuid4()))

@dataclass
class FaceObservation(BaseObservation):
    """A raw face detection before identity resolution."""
    embedding: List[float]
    bbox: List[int]
    base64_img: str
    detection_score: float
    quality_score: float
    # After resolution, this links to a Global Entity
    entity_id: Optional[str] = None 

@dataclass
class VoiceObservation(BaseObservation):
    """A raw snippet of speech."""
    embedding: List[float]
    asr_text: str
    start_sec: float
    end_sec: float
    # After resolution, this links to a Global Entity
    entity_id: Optional[str] = None

@dataclass
class VisualObservation(BaseObservation):
    """Global frame context (CLIP + OCR + Objects)."""
    clip_embedding: List[float]
    ocr_tokens: List[Dict[str, Any]]  # List of {"text": str, "conf": float}
    detected_objects: List[str]

@dataclass
class MemoryNode:
    """A high-level thought or description generated by the agent."""
    video_id: str
    content: str
    mem_type: MemoryType
    embedding: Optional[List[float]] = None
    clip_id: Optional[int] = None
    mem_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    
    # 🔥 CRITICAL: List of entity_ids (UUIDs) mentioned in this text.
    # This is how we build the Neo4j [MENTIONS] edges.
    linked_entities: List[str] = field(default_factory=list)

@dataclass
class GlobalEntity:
    """A unique Person or Object tracked across the entire video (or library)."""
    entity_id: str
    entity_type: EntityType
    video_id: str
    
    # Metadata used to describe the entity (e.g., "The man in the blue shirt")
    canonical_name: Optional[str] = None
    attributes: Dict[str, Any] = field(default_factory=dict)
    
    # Represetative embeddings for search
    face_embeddings: List[List[float]] = field(default_factory=list)
    voice_embeddings: List[List[float]] = field(default_factory=list)